[flavor]
dark = "catppuccin-mocha"

[icon]
# https://emojis.wiki/
prepend_conds = [
  { if = "hidden & dir",  text = "👻" },  # Hidden directories
  { if = "dir",           text = "📁" },  # Directories
  { if = "!(dir | link)", text = "📄" },  # Normal files (not directories or symlinks)
]
