[mgr]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
linemode = "permissions"
show_symlink = true

[opener]
playmusic = [
  { run = 'clementine "$@"', orphan = true, for = "linux" },
]
playvideo = [
  { run = 'vlc "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
  { name = "*.mp3", use = "playmusic" },
  { mime = "video/*", use = "playvideo" },
]

[which]
sort_sensitive = true
sort_reverse = false
